services:
  -type: web
  name: smallscapesproject
  env: python
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn smallscapesproject.wsgi:application
  staticFiles:
    -baseDirectory: static
    servePath: /
